ktor:
    application:
        modules:
            - dev.ch8n.sample.ApplicationKt.module
    deployment:
        port: 8000

jwt:
    secret : "9999999999"
    issuer : "http://0.0.0.0:8000"
    audience : "http://0.0.0.0:8000"
    realm : "collectiondb.com"